version: '3.8'

services:
  discord-reminder-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-reminder-bot
    restart: unless-stopped
    environment:
      # Discord Configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}

      # Database Configuration
      - DATABASE_URL=${DATABASE_URL:-./data/discord_bot.db}

      # Reminder Configuration
      - REMINDER_INTERVAL_HOURS=${REMINDER_INTERVAL_HOURS:-24}
      - USE_SEPARATE_REMINDER_CHANNEL=${USE_SEPARATE_REMINDER_CHANNEL:-false}
      - REMINDER_CHANNEL_NAME=${REMINDER_CHANNEL_NAME:-rappels-events}

      # Auto-deletion Configuration
      - AUTO_DELETE_REMINDERS=${AUTO_DELETE_REMINDERS:-true}
      - AUTO_DELETE_DELAY_HOURS=${AUTO_DELETE_DELAY_HOURS:-1}

      # Permission Configuration
      - ADMIN_ROLES=${ADMIN_ROLES:-Admin,Moderateur,Coach}

      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_TO_FILE=${LOG_TO_FILE:-true}
      - LOG_COLORS=${LOG_COLORS:-false}

      # Error Recovery Configuration
      - ERROR_RECOVERY_MAX_RETRIES=${ERROR_RECOVERY_MAX_RETRIES:-3}
      - ERROR_RECOVERY_BASE_DELAY=${ERROR_RECOVERY_BASE_DELAY:-1.5}
      - ERROR_RECOVERY_MAX_DELAY=${ERROR_RECOVERY_MAX_DELAY:-60}
      - ERROR_RECOVERY_ENABLE_STATS=${ERROR_RECOVERY_ENABLE_STATS:-true}

      # Production Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - TZ=${TZ:-Europe/Paris}

      # Test Mode (optional)
      - TEST_MODE=${TEST_MODE:-false}

    volumes:
      # Data persistence
      - ./data:/app/data
      # Logs persistence (optional)
      - ./logs:/app/logs

    # Health check - verify bot is running properly
    healthcheck:
      test: ['CMD', 'node', '-e', "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - bot-network

    # Security - Use the app user created in Dockerfile
    user: "1001:1001"

    # Resource limits optimized for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  bot-network:
    driver: bridge
