#!/bin/bash
# Demo script to showcase help command and interval features

echo "🎬 Discord Reminder Bot - Demo Help & Intervals"
echo "================================================"

echo ""
echo "📋 Available slash commands:"
echo "  /watch <message> [interval] - Monitor message reactions with reminders"  
echo "  /unwatch <message>          - Stop monitoring a message"
echo "  /list                       - List all watched matches on this server"
echo "  /remind [message]           - Send manual reminder (all if no message)"
echo "  /status <message>           - Show detailed status of a reminder"
echo "  /pause <message>            - Pause reminders for a message"
echo "  /resume <message>           - Resume paused reminders"
echo "  /set_interval <message> <interval> - Change reminder interval"
echo "  /health                     - Show bot health and error recovery stats"
echo "  /help                       - Show comprehensive help"
echo "  /sync                       - Sync slash commands (dev only)"

echo ""
echo "⏰ Available intervals:"
echo "  • 30 seconds (test mode)"
echo "  • 1 minute (test mode)" 
echo "  • 2 minutes (test mode)"
echo "  • 5 minutes"
echo "  • 15 minutes"
echo "  • 30 minutes"
echo "  • 1 hour (default)"
echo "  • 2 hours"
echo "  • 6 hours"  
echo "  • 12 hours"
echo "  • 24 hours"

echo ""
echo "🧪 Test Mode Features:"
echo "  • Short intervals (30s, 1min, 2min) for development"
echo "  • Set TEST_MODE=true in .env"
echo "  • Real-time testing with quick feedback"
echo "  • Debug logging for detailed monitoring"

echo ""
echo "🏗️ Architecture:"
echo "  • Dynamic scheduling system (±5s precision)"
echo "  • Intelligent sleep mode (0% CPU when idle)"
echo "  • Error recovery with retry statistics"
echo "  • Multi-server support with per-server permissions"
echo "  • Modular codebase (commands/, config/, models/, etc.)"

echo ""
echo "🎉 Demo complete! Use /help in Discord for interactive help."