name: CI - Tests and Quality Checks

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch: # Allow manual triggers

env:
  # Global environment variables to optimize pip
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_NO_CACHE_DIR: 0
  PYTHONUNBUFFERED: 1

jobs:
  lint-and-format:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install audioop-lts  # Python 3.13 compatibility
    
    - name: Code formatting check (Black)
      run: |
        black --check --diff .
    
    - name: Import sorting check (isort)
      run: |
        isort --check-only --diff .
    
    - name: Linting (flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    
    - name: Type checking (mypy)
      run: |
        mypy . --ignore-missing-imports
      continue-on-error: true  # Allow mypy to fail without breaking CI
    
    - name: Security linting (bandit)
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . --severity-level medium
      continue-on-error: true
    
    - name: Dependency vulnerability scan (safety)
      run: |
        safety check --json --output safety-report.json || true
        safety check
      continue-on-error: true

    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
        retention-days: 30

  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false  # Continue other matrix jobs even if one fails

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        if [ "${{ matrix.python-version }}" = "3.13" ]; then
          pip install audioop-lts
        fi
    
    - name: Create test environment file
      run: |
        cat > .env << EOF
        DISCORD_TOKEN=test_token_for_ci
        TEST_MODE=true
        LOG_LEVEL=DEBUG
        LOG_TO_FILE=false
        REMINDER_INTERVAL_HOURS=0.0167
        EOF
    
    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term-missing --cov-report=html --junitxml=pytest.xml
      env:
        PYTHONPATH: .
        TEST_MODE: true
        DISCORD_TOKEN: test_token_for_ci

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.13'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          htmlcov/
          coverage.xml
          pytest.xml
        retention-days: 7

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [lint-and-format, test]
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image (test)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: discord-reminder-bot:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        outputs: type=docker,dest=/tmp/discord-bot.tar

    - name: Load Docker image
      run: |
        docker load -i /tmp/discord-bot.tar

    - name: Test Docker image
      run: |
        # Test that the image can be created and basic imports work
        timeout 60s docker run --rm --env DISCORD_TOKEN=test_token discord-reminder-bot:test python -c "
        import sys
        print(f'Python version: {sys.version}')
        
        # Test core imports
        import discord
        print('✓ discord.py imported successfully')
        
        from bot import create_bot
        print('✓ Bot creation import successful')
        
        from utils.logging_config import setup_logging
        setup_logging(log_to_file=False)
        print('✓ Logging system works')
        
        print('✓ All basic functionality tests passed')
        "
    
    - name: Test Docker compose configuration
      run: |
        # Create minimal test environment
        echo "DISCORD_TOKEN=test_token" > .env
        
        # Test docker-compose configuration
        docker-compose config
        
        echo "✓ Docker Compose configuration is valid"

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [docker-build]
    timeout-minutes: 10
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install audioop-lts
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --tb=short
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_TEST }}
        TEST_MODE: true
        LOG_LEVEL: DEBUG

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    if: always()
    needs: [lint-and-format, test, docker-build]

    steps:
    - name: Check results
      run: |
        echo "## CI Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Lint and Format: ${{ needs.lint-and-format.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Tests: ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Docker Build: ${{ needs.docker-build.result }}" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ needs.lint-and-format.result }}" = "failure" ] || [ "${{ needs.test.result }}" = "failure" ] || [ "${{ needs.docker-build.result }}" = "failure" ]; then
          echo "❌ CI failed - see individual job logs for details" >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "✅ All CI checks passed successfully" >> $GITHUB_STEP_SUMMARY
        fi
